### ISSUE TITLE
why use function as the target of Proxy

### ISSUE THREAD

**Issue by henrycjchen** [CntChen/moebius-object#2]
the syntax of Proxy is: `let p = new Proxy(target, handler);`
the target can be an object, an array or a function. 
why don't you use a plain object as target directly?

**Comment by CntChen** [comment]
Good question.
A moebius object `p`, usage not only call by `p.xxx`, but also `p.xxx()`.
Function as the target of Proxy, when get property `xxx` from the Proxy, we can execute `xxx` as a function.
